### ISSUE TITLE
TODO List for 1.0.0 (and beyond)

### ISSUE THREAD

**Issue by ashquarky** [QuarkTheAwesome/AMCSAPI#1]
Here's the official TODO list for AMCSAPI v1; the first non-development release.
- [x] Connecting to a server
- [x] Basic chat I/O
- [x] Server list ping (not query, which is different)
- [ ] Anything else I stumble across in the MCC source that I think is cool

And here's a few things I want done in the future (because I can) but not in this release:
- [ ] Access to all packets
- [ ] Simple movement engine (probably won't happen)

Feel free to comment any new features and stuff here. Seriously, please do.

**Comment by moderatorman** [comment]
I hadn't gotten to reading this before creating a new Issue. But I suggested something in the comments  of that issue that I think you might find useful to developers.

**Comment by moderatorman** [comment]
I know this kind of discussion doesn't go here, but you might be interested in one of my projects. I'm currently trying to create a chat program that allows the user to join with whatever login they want to use, and send the server messages/commands. And I think your idea for a movement engine is a great idea, because then if you wanted to make a chat program (like mine) be able to chat on Mineplex, you would have to make the player move from spawn.

**Comment by moderatorman** [comment]
All you really have to do is have something like, mc.move(Int, Int)
First number could be X, second number could be Z. All you would have to do is make the engine walk to those coords. You could add something like, mc.jump() or something like that. Or you could add a Y coord to the mc.move and give it slightly more complicated path finding. You could have a plugin that manages this API's movement engine/pathfinding.

**Comment by moderatorman** [comment]
I know you designed it to be in one method, but you should change that. You know how you made the setup process? ( Dim WithEvents mc as New Server() ) Well you should change it to something like ( Dim WithEvents auth As AMCSAPI.authenticate ) or something similar. I would like to have multiple control methods. Such as an "Authenticate" button, a "Connect" button, and a "Send message" button.

**Comment by moderatorman** [comment]
I don't know how many people know about this API, or use it, but if you made this a little easier to use, and a little less light-weight you could get a lot of developers to use this API. Imagine adding a web feature, so you can use this API with JSON. Or even better, with almost any programming language. You just need to make it a little more beefy. You need to make it slightly more complicated to use. (But not TOO complicated, obviously.)

**Comment by ashquarky** [comment]
@CraftLifeGaming It's been a long time since I worked on this project (or really played Minecraft at all). My interests have moved on (to the Wii U to be more precise) so I probably won't restart work on this API unless I have a relapse or something. As for your questions, I'm probably not going to get around to making a movement engine and it's also worth noting that there's no reason this wouldn't work in Visual C#. I'll quickly answer your other questions in their respective issues.

I am completely open to pull requests, however!
